FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/index.html

###################################################################################
# notice that we did not add an ENTRYPOINT or a CMD to our Dockerfile. 
# We will use the underlying ENTRYPOINT and CMD provided by the base NGINX image.
###################################################################################